language: node_js
node_js:
  - "node"
  - "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn test --coverage
  - yarn build
before_script:
cache:
  yarn: true
after_script:
  - bash <(curl -s https://codecov.io/bash)