version: '3'

volumes:
  node_modules:

services:
  app:
    image: library/node:9.11.1
    working_dir: /app
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: bash -c "yarn && yarn start"