/*
*  DO NOT EDIT THIS FILE, IF YOU NEED TO MAKE CHANGES TO THE CONFIG USE THE PROVIDED METHODS AND EDIT YOUR webpack.config.js in the root of the project
*  Thanks :)
* */

"use strict";

const Config = require("./Config");
const webpack = require("webpack");

class DevConfig extends Config {
    getPlugins() {
        return Object.assign(super.getPlugins(), [
            new webpack.HotModuleReplacementPlugin()
        ]);
    }

    build() {
        return Object.assign(super.build(), {
            mode: "development",
            devtool: "source-map"
        });
    }
}

module.exports = DevConfig;
