/*
*  DO NOT EDIT THIS FILE, IF YOU NEED TO MAKE CHANGES TO THE CONFIG USE THE PROVIDED METHODS AND EDIT YOUR webpack.config.js in the root of the project
*  Thanks :)
* */

"use strict";

const Config = require("./Config");
const path = require("path");

class ProductionConfig extends Config {
    constructor() {
        super();
        this.mDist = "dist";
    }

    getEntry() {
        return {
            [this.mPackage]: path.join(process.cwd(), `src/${this.mPackage}.ts`)
        };
    }

    getRules() {
        return Object.assign(super.getRules(), [
            {
                test: /\.tsx?$/,
                use: [
                    {
                        loader: "ts-loader",
                        options: {
                            configFile: path.join(
                                process.cwd(),
                                "tsconfig.json"
                            ),
                            compilerOptions: {
                                declaration: true,
                                declarationDir: ""
                            }
                        }
                    }
                ],
                exclude: /node_modules/
            }
        ]);
    }

    build() {
        return Object.assign(super.build(), {
            mode: "production",
            optimization: {
                minimize: true
            }
        });
    }
}

module.exports = ProductionConfig;
